openapi: 3.0.0
info:
  title: Bike Rental API
  version: '1.0'
  termsOfService: 'https://db.de'
servers:
  - url: 'https://api.db.de/bikerental/v1'
paths:
  /stations:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/station'
      operationId: get-stations
      description: Stationsübersicht
      parameters:
        - schema:
            type: number
          in: query
          name: lat
          description: Latitude
        - schema:
            type: number
          in: query
          name: lng
          description: Longitude
  /rentals:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/rentalRequest'
      operationId: get-rentals
      description: Ausleihe Historie
    post:
      summary: ''
      operationId: post-rentals
      responses:
        '201':
          description: Created
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      description: Ausleihe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rentalRequest'
          application/xml:
            schema:
              type: object
              properties: {}
          application/javascript:
            schema:
              type: object
              properties: {}
          multipart/form-data:
            schema:
              type: object
              properties: {}
        description: ''
  '/rentals/{rentalId}':
    parameters:
      - schema:
          type: string
        name: rentalId
        in: path
        required: true
    delete:
      summary: ''
      operationId: delete-rentals-rentalId
      responses:
        '204':
          description: No Content
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      description: Stornieren
  '/rentals/{rentalId}/destinationStation':
    parameters:
      - schema:
          type: string
        name: rentalId
        in: path
        required: true
    patch:
      summary: ''
      operationId: patch-rentals-rentalId-destinationStation
      responses:
        '204':
          description: No Content
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      requestBody:
        content:
          application/json:
            schema:
              type: integer
components:
  schemas:
    station:
      title: station
      type: object
      description: ''
      properties:
        id:
          type: integer
        name:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        availableBikes:
          type: integer
    rentalRequest:
      title: rentalRequest
      type: object
      description: ''
      properties:
        startStation:
          type: string
        destinationStation:
          type: string
        bikeNumber:
          type: string
    error:
      title: error
      type: object
      description: ''
      properties:
        errorMessage:
          type: string
    rentalHistory:
      title: rentalHistory
      type: object
      properties:
        id:
          type: string
        startStation:
          type: string
        destinationStation:
          type: string
        startDate:
          type: string
          format: date-time
        destinationDate:
          type: string
          format: date-time
